
name: CI/CD Pipeline

# Controls when the workflow will run
on:
  push:
    branches: [main]
    
env:
  REGISTRY_NAME: customerserviceregistry
  CLUSTER_NAME: customerserviceCluster
  CLUSTER_RESOURCE_GROUP: customerserviceResources
  NAMESPACE: default
  APP_NAME: customerservice
  
jobs:
  customer-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run shell script
        run: echo commit hash is ${{ github.sha }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./customerService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/customerservice:${{ github.sha }}
          
  product-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run shell script
        run: echo commit hash is ${{ github.sha }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./productService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/customerservice:${{ github.sha }}

  delivery-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run shell script
        run: echo commit hash is ${{ github.sha }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deliveryService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/customerservice:${{ github.sha }}


          
       
